#!/bin/bash
# git-mine-commit - A mining algorithm for git commits
# Copyright (C) 2014 Franck Verrot <franck@verrot.fr>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

mine() {
  local prefix=$1
  local max_iterations=$2
  local commit_object=`git cat-file -p HEAD`

  echo "$commit_object"
  echo -en "Mining HEAD's sha1..."
  for i in $(seq 0 $max_iterations)
  do
    echo -n "."
    new_sha1=`echo -e "$commit_object\n\n[$i]" | git hash-object -t commit --stdin`


    if [[ $new_sha1 == $prefix* ]]; then
      echo -e "\t [OK] ($i iterations)"
      echo -e "$commit_object\n\n[$i]" | git hash-object -t commit -w --stdin
      echo -e "\nPreimage Found! $new_sha1\n"
      exit 0
    else
      let "val=$i % 70"
      if [ $val -eq 0 ]; then
        echo " " $i
      fi
    fi
  done
  echo -e "\t[KO] (Reached max iterations of $max_iterations>)"
  exit 1
}

prefix=$1
max_iterations=$2

if [[ $prefix == "" ]]; then
  echo "usage: `basename $0` <prefix> <max_iteration (default: 1M)"
  echo -e "\te.g: git mine-commit 31337 100"
  exit 1
else
  if [[ $max_iterations == "" ]]; then
    max_iterations=1000000
  fi

  mine $prefix $max_iterations
fi
